load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "binary_counter_main",
    srcs = ["binary_counter_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

